steps:
  - id: 'terraform format'
    name: 'hashicorp/terraform:0.15.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform fmt -check -diff -recursive || exit 1
    timeout: 60s
  - id: 'terraform validate'
    name: 'hashicorp/terraform:0.15.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        current_path=`pwd`
        for folder in `find ./gcp -type d`
        do
          cd ${folder}
          echo "[INFO] - Validant els fitxers de terraform al directori ${folder}"
          terraform init -backend=false || exit 1
          terraform validate || exit 1
          cd ${current_path}
        done
    timeout: 60s
