steps:
  - id: 'terraform plan'
    name: 'hashicorp/terraform:0.15.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        current_path=`pwd`
        for folder in `find ./gcp/${_ENVIRONMENT} -type d`
        do
          cd ${folder}
          if ls *.tf &>/dev/null; then
            echo "[INFO] - Visualitzant els canvis d'infraestructura a aplicar en el directori ${folder}"
            terraform init || exit 1
            terraform plan || exit 1
          else
            echo "[INFO] - No s'han trobat arxius de terraform en el directori ${folder}"
          fi
          cd ${current_path}
        done
    timeout: 60s
  - id: 'terraform apply'
    name: 'hashicorp/terraform:0.15.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        current_path=`pwd`
        for folder in `find ./gcp/${_ENVIRONMENT} -type d`
        do
          cd ${folder}
          if ls *.tf &>/dev/null; then
            echo "[INFO] - Aplicant canvis d'infraestructura en el directori ${folder}"
            terraform init || exit 1
            terraform apply -auto-approve || exit 1
          else
            echo "[INFO] - No s'han trobat arxius de terraform en el directori ${folder}"
          fi
          cd ${current_path}
        done
    timeout: 60s
