steps:
  - id: 'terraform format'
    name: 'hashicorp/terraform:0.15.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform fmt -check -diff -recursive
  - id: 'terraform validate'
    name: 'hashicorp/terraform:0.15.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        current_path=`pwd`
        for folder in `find . -type d`
        do
          cd ${folder}
          echo "[INFO] - Validating terraform files in path ${folder}"
          terraform init -backend=false || exit 1
          terraform validate || exit 1
          cd ${current_path}
        done
